name: iOS Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configurar Xcode
        run: |
          xcodebuild -version 16.0
      - name: Construir la aplicación
        run: |
          xcodebuild clean build  \
          -project LiteTest.xcodeproj  \
          -scheme LiteTest  \
          -sdk iphoneos  \
          -configuration Debug  \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
